name: CI/CD for Rock RMS

on:
  push:
    branches:
      - ci-cd
  pull_request:
    branches:
      - ci-cd

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up .NET Framework and Visual Studio components
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'

      # Step 3: Install NuGet packages for Rock RMS
      - name: Install NuGet packages
        run: nuget restore Rock.sln

      # Step 4: Build the solution using MSBuild
      - name: Build Rock RMS
        run: msbuild Rock.sln /p:Configuration=Release

  