name: CI/CD for Rock RMS

on:
  push:
    branches:
      - ci-cd
  pull_request:
    branches:
      - ci-cd

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Install NuGet packages for Rock RMS
      - name: Install NuGet packages
        run: nuget restore Rock.sln

      # Step 4: Build the solution using MSBuild
      - name: Build Rock RMS
        run: msbuild Rock.sln /p:Configuration=Release

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app for release
        run: msbuild Rock.sln -property:Configuration=Release